### ISSUE TITLE
Issues when testing the function with real data

### ISSUE THREAD

**Issue by rladhania** [wustat/rjaf#4]
Issues that popped up while testing (will keep updating this list as more come up)

1. when  clus.tree.growing = T, the function is executed only when the treatment arm is named as "trt". Any other name such as "arm", even when explicitly specified in the function call (trt = "arm") throws up an error. This problem doesn't arise during the unclustered execution (clus.tree.growing = F). 
2. When clus.tree.growing = T, can we also send as function output the treatment clusters (which arms were clustered together)? That will be useful info for the social science researcher/application folks to get a sense of which arms are being clustered together, and if any meaningful patterns arise.
3.  Can we make the prob argument optional?

**Comment by XinyiEmilyZhang** [comment]
@rladhania Thanks for checking! I’ve resolved the potential issue related to error 1 and tested it with sample data where "arm" was used as the treatment name. Could you confirm if this fix works with the real dataset as well?
